export const systemRouter = [
  {
    "translation": null,
    "menuId": "4183b61b5f1911ebb98c0242ac11000e",
    "menuName": "系统管理",
    "menuIcon": "SettingOutlined",
    "menuType": "00015",
    "remark": "管理项目",
    "redirect": null,
    "order": 5,
    "fold": null,
    "hidden": false,
    "subMenu": [
      {
        "translation": null,
        "menuId": "418421325f1911ebb98c0242ac11000e",
        "menuName": "用户管理",
        "menuIcon": null,
        "menuType": "00015",
        "remark": "管理项目",
        "redirect": null,
        "order": 2,
        "fold": null,
        "hidden": false,
        "subMenu": null,
        "columns": null,
        "inputs": null,
        "reMethod": null,
        "menuUrl": "/system/users",
        "reComponent": "pages/System/User"
      },
      {
        "translation": null,
        "menuId": "4183be9a5f1911ebb98c0242ac11000e",
        "menuName": "角色管理",
        "menuIcon": null,
        "menuType": "00015",
        "remark": "管理项目",
        "redirect": null,
        "order": 5,
        "fold": null,
        "hidden": false,
        "subMenu": null,
        "columns": null,
        "inputs": null,
        "reMethod": null,
        "menuUrl": "/system/roles",
        "reComponent": "pages/System/Role"
      },
      {
        "translation": null,
        "menuId": "41841d515f1911ebb98c0242ac11000e",
        "menuName": "企业管理",
        "menuIcon": null,
        "menuType": "00015",
        "remark": "管理项目",
        "redirect": null,
        "order": 7,
        "fold": null,
        "hidden": false,
        "subMenu": null,
        "columns": null,
        "inputs": null,
        "reMethod": null,
        "menuUrl": "/system/company",
        "reComponent": "pages/System/Company"
      },
      {
        "translation": null,
        "menuId": "418414eb5f1911ebb98c0242ac11000e",
        "menuName": "规则应用管理",
        "menuIcon": null,
        "menuType": "00015",
        "remark": "管理项目",
        "redirect": null,
        "order": 19,
        "fold": null,
        "hidden": false,
        "subMenu": null,
        "columns": null,
        "inputs": null,
        "reMethod": null,
        "menuUrl": "/system/rules",
        "reComponent": "pages/System/Rule"
      },
      {
        "translation": null,
        "menuId": "418419805f1911ebb98c0242ac11000e",
        "menuName": "业务稿件库管理",
        "menuIcon": null,
        "menuType": "00015",
        "remark": "管理项目",
        "redirect": null,
        "order": 26,
        "fold": null,
        "hidden": false,
        "subMenu": null,
        "columns": null,
        "inputs": null,
        "reMethod": null,
        "menuUrl": "/system/business",
        "reComponent": "pages/System/Business"
      }
    ],
    "columns": null,
    "inputs": null,
    "reMethod": null,
    "menuUrl": "/system",
    "reComponent": "layouts/BlankLayout"
  }
]
