export const toolRouter = [
  {
    "translation": null,
    "menuId": "4183b61b5f1911ebb98c0242ac11001e",
    "menuName": "工具",
    "menuIcon": "ToolOutlined",
    "menuType": "00015",
    "remark": "工具",
    "redirect": null,
    "order": 5,
    "fold": null,
    "hidden": false,
    "subMenu": [
      {
        "translation": null,
        "menuId": "418421325f1911ebb98c0242ac11000e",
        "menuName": "图表",
        "menuIcon": null,
        "menuType": "00015",
        "remark": "图表",
        "redirect": null,
        "order": 1,
        "fold": null,
        "hidden": false,
        "subMenu": null,
        "columns": null,
        "inputs": null,
        "reMethod": null,
        "menuUrl": "/tools/charts",
        "reComponent": "pages/Tools/Charts"
      },
      {
        "translation": null,
        "menuId": "418421325f1911ebb98c0242ac11000e",
        "menuName": "二维码",
        "menuIcon": null,
        "menuType": "00015",
        "remark": "二维码",
        "redirect": null,
        "order": 1,
        "fold": null,
        "hidden": false,
        "subMenu": null,
        "columns": null,
        "inputs": null,
        "reMethod": null,
        "menuUrl": "/tools/qrcode",
        "reComponent": "pages/Tools/Code"
      },
      {
        "translation": null,
        "menuId": "418421325f1911ebb98c0242ac11000f",
        "menuName": "头像截图",
        "menuIcon": null,
        "menuType": "00016",
        "remark": "截图",
        "redirect": null,
        "order": 2,
        "fold": null,
        "hidden": false,
        "subMenu": null,
        "columns": null,
        "inputs": null,
        "reMethod": null,
        "menuUrl": "/tools/cropper",
        "reComponent": "pages/Tools/Cropper"
      },
    ],
    "columns": null,
    "inputs": null,
    "reMethod": null,
    "menuUrl": "/tools",
    "reComponent": "layouts/BlankLayout"
  }
]
